format_version: 3
pipelines:
  task-pipeline:
    lock_behavior: lockOnFailure
    group: TEST
    materials:
      repo: 
        git: https://github.com/Chritian92/CG.git
        branch: new_changes
    stages: 
      - Build:
          jobs:
            Building: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "gradle/quickstart"
              artifacts:
                - build:
                    source: gradle/quickstart/build/libs/*.jar
                    destination: build

      - Test:
          jobs:
            Publishing: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - clean
                      - test
                      - -p
                      - gradle/quickstart
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - clean
                      - test
                      - jacocoTestReport
                      - -p
                      - gradle/quickstart/
              artifacts:
                - build:
                    source: gradle/quickstart/build/reports/tests/test/*
                    destination: html_report
                - test:
                    source: gradle/quickstart/build/test-results/test/*xml
                    destination: xml
              tabs:
                Xml_Test_Result: xml/TEST-org.gradle.PersonTest.xml
                Test_Summary: html_report/index.html
                
      - CodeQuality:
          jobs:
            CodeQuality: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - sonarqube
                      - -p
                      - gradle/quickstart/

  webapp-quickstart:
    lock_behavior: lockOnFailure
    group: Application
    materials:
      repo:
        git: https://github.com/Chritian92/CG.git
        branch: new_changes
        whitelist:
            - webapp-quickstart/**/*
    stages:
      - Build:
          jobs:
            Building:
              tasks:
                - exec:
                    command: ./webapp-quickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "webapp-quickstart"
              artifacts:
                - build:
                    source: webapp-quickstart/build/libs/*.war
                    destination: war
      
      - Deploy:
          jobs:
            Application:
              tasks:
                - fetch:
                    stage: Build
                    job: Building
                    source: war/
                - exec:
                    command: ./webapp-quickstart/gradlew
                    arguments:
                      - -b
                      - deploy.gradle
                      - deploy
                      - -Pdev_server=10.28.135.237
                      - -Pwar_path=war
                      - -p
                      - webapp-quickstart
