fformat_version: 3
pipelines:
  task-pipeline:
    lock_behavior: lockOnFailure
    group: TEST
    materials:
      repo: 
        git: https://github.com/devops-at06/CG.git
        branch: master
    stages: 
      - Build:
          jobs:
            Building: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "gradle/quickstart"
              artifacts:
                - build:
                    source: gradle/quickstart/build/libs/*.jar
                    destination: build

      - Test:
          jobs:
            Publishing: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - clean
                      - test
                      - -p
                      - gradle/quickstart
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - clean
                      - test
                      - jacocoTestReport
                      - -p
                      - gradle/quickstart/
              artifacts:
                - build:
                    source: gradle/quickstart/build/reports/tests/test/*
                    destination: html_report
                - test:
                    source: gradle/quickstart/build/test-results/test/*xml
                    destination: xml
              tabs:
                Xml_Test_Result: xml/TEST-org.gradle.PersonTest.xml
                Test_Summary: html_report/index.html
                
      - CodeQuality:
          jobs:
            CodeQuality: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - sonarqube
                      - -p
                      - gradle/quickstart/

  webapp-quickstart:
    lock_behavior: lockOnFailure
    group: Application
    materials:
      repo:
        git: https://github.com/devops-at06/CG.git
        branch: master
    stages:
      - Commit:
          jobs:
            Building:
              tasks:
                - exec:
                    command: ./webapp/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "webapp"
              artifacts:
                - build:
                    source: webapp/build/libs/*.war
                    destination: war
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./webapp/gradlew
                    arguments:
                      - tests
                      - -p
                      - webapp
              artifacts:
                - build:
                    source: webapp/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: webapp/build/test-results/test/*.xml
                    destination: xml
              tabs:
                unit_test: html/index.html
      - Deploy:
          jobs:
            Application:
              tasks:
                - exec:
                    command: ./webapp/gradlew
                    arguments:
                      - -b
                      - webapp/deploy.gradle
                      - deploy
                      - -Pdev_server=10.28.135.237
                      - -p
                      - webapp
